### ISSUE TITLE
Comments missing

### ISSUE THREAD

**Issue by ixolan** [amethyst/evoli#45] opened 2019-05-03 14:59 UTC
Hello,
please add much more comments and descriptions in the source code. Because this project should be a showcase for amethyst and also a basic resource for new developers trying to 
use and learn amethyst, there needs to be much more information's in the source code. Right now its only code without any comments.

rgds
Martin

**Comment by erlend-sh** [comment] 2019-05-03 15:17
Hey Martin,

We are in agreement, the code needs more comments in order to be more beginner-friendly. For the time being though we just gotta stay in "game making mode" for a while so that we can finish the [MVP spec](https://community.amethyst.rs/t/evoli-mvp-specification/487) (see also the MVP milestone). Following that release we will take some time to document everything we've made so far.

This intention is documented in our [Introduction doc](https://community.amethyst.rs/t/evoli-introduction/770):

> at a certain major iteration, a LTS if you will, we’re gonna hit pause on development and only document the status quo for a while. This (a) improves our codebase’s value as a teaching-game for Amethyst, (b) provides an excellent contributor pipeline for us and (c ) will be praised by our future selves whenever we’re coming back to make small or big changes.

In the meantime please ask us any code questions you'd like on our forum or chat. The answers you help produce will form the foundation of our official documentation.

**Comment by erlend-sh** [comment] 2019-05-04 06:12
As this is not a bug or completed feature spec I’m gonna close it as resolved. Similar questions can be asked in our forum,

**Closed as completed by erlend-sh** 2019-05-04 06:12 UTC
